---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polynomio
spec:
  ## Change this to more than 2 if you are going for multiple pod instances
  replicas: 1
  strategy:
    rollingUpdate:
      ## allow max 1 new/extra pods at a time when rolling
      maxSurge: 1
      ## allow max 0 pod to be unavailable while the new one is not yet available                   
      maxUnavailable: 0             
  selector:
    matchLabels:
      app: polynomio
  template:
    metadata:
      labels:
        app: polynomio
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: polynomio
        image: docker.io/jayaprabahar/polynomio:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: polynomio
spec:
  ports:
  - port: 8080
  selector:
    app: polynomio
